# ---------------------------------------------------------------------------
# Drone Storage — GCS bucket for drone capture data
#
# Bucket layout:
#   captures/{capture_id}/raw/{filename}         ← pre-signed PUT target
#   captures/{capture_id}/processed/             ← ODM LAS output
#   captures/{capture_id}/tiles/                 ← Potree octree tiles (public)
#
# Pre-signed URLs (V4, 15-min TTL) are generated by ft-api for direct browser
# uploads to raw/. ft-api never handles the binary payload.
# ---------------------------------------------------------------------------

locals {
  bucket_name = "flowterra-drone-${var.env}"
}

resource "google_project_service" "storage" {
  project            = var.project_id
  service            = "storage.googleapis.com"
  disable_on_destroy = false
}

# ---------------------------------------------------------------------------
# GCS Bucket
# ---------------------------------------------------------------------------

resource "google_storage_bucket" "drone" {
  project                     = var.project_id
  name                        = local.bucket_name
  location                    = var.location
  storage_class               = "STANDARD"
  uniform_bucket_level_access = true
  labels                      = var.labels

  cors {
    origin          = ["*"]
    method          = ["GET", "PUT", "HEAD", "OPTIONS"]
    response_header = ["Content-Type", "Content-MD5", "x-goog-resumable"]
    max_age_seconds = 3600
  }

  depends_on = [google_project_service.storage]
}

# ---------------------------------------------------------------------------
# IAM — public read on tiles/ prefix only (MVP)
# Requires uniform bucket-level access; uses an IAM condition scoped to the
# captures/*/tiles/ path so raw and processed objects stay private.
# ---------------------------------------------------------------------------

resource "google_storage_bucket_iam_member" "public_tiles_reader" {
  bucket = google_storage_bucket.drone.name
  role   = "roles/storage.objectViewer"
  member = "allUsers"

  condition {
    title       = "tiles_prefix_only"
    description = "Public read scoped to captures/*/tiles/ prefix."
    expression  = "resource.name.startsWith(\"projects/_/buckets/${local.bucket_name}/objects/\") && resource.name.contains(\"/tiles/\")"
  }
}

# ---------------------------------------------------------------------------
# IAM — ft-api SA: full object access (upload raw, read processed, write tiles)
# ---------------------------------------------------------------------------

resource "google_storage_bucket_iam_member" "ft_api_object_admin" {
  bucket = google_storage_bucket.drone.name
  role   = "roles/storage.objectAdmin"
  member = "serviceAccount:${var.ft_api_sa_email}"
}

# ---------------------------------------------------------------------------
# IAM — ft-api SA: signBlob on itself
# Required for V4 signed URL generation when running as a Cloud Run workload.
# Without this, GenerateSignedUrl raises SigningError / 403.
# ---------------------------------------------------------------------------

resource "google_service_account_iam_member" "ft_api_token_creator" {
  service_account_id = "projects/${var.project_id}/serviceAccounts/${var.ft_api_sa_email}"
  role               = "roles/iam.serviceAccountTokenCreator"
  member             = "serviceAccount:${var.ft_api_sa_email}"
}
