# ---------------------------------------------------------------------------
# BigQuery — dataset and tables for Flowterra analytics
#
# Tables:
#   location_events  — streaming inserts from ingest-fn (partitioned by day)
#   geofence_events  — geofence entry/exit alerts from ingest-fn
#
# Dataset ID follows the naming convention: flowterra_{env}
# (e.g. flowterra_dev, flowterra_demo, flowterra_prod)
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# Required APIs
# ---------------------------------------------------------------------------

resource "google_project_service" "bigquery" {
  project            = var.project_id
  service            = "bigquery.googleapis.com"
  disable_on_destroy = false
}

# ---------------------------------------------------------------------------
# Dataset
# ---------------------------------------------------------------------------

resource "google_bigquery_dataset" "flowterra" {
  project    = var.project_id
  dataset_id = var.dataset_id
  location   = var.bq_location

  description                     = "Flowterra analytics dataset (${var.env} environment)."
  default_table_expiration_ms     = null # tables never auto-expire
  default_partition_expiration_ms = null

  labels = var.labels

  # Restrict access: only ingest-fn SA (writer) and ft-api SA (reader).
  # Additional analysts can be granted via the GCP console.
  access {
    role          = "OWNER"
    special_group = "projectOwners"
  }

  access {
    role          = "WRITER"
    user_by_email = var.ingest_fn_sa_email
  }

  dynamic "access" {
    for_each = var.ft_api_sa_email != "" ? [var.ft_api_sa_email] : []
    content {
      role          = "READER"
      user_by_email = access.value
    }
  }

  depends_on = [google_project_service.bigquery]
}

# ---------------------------------------------------------------------------
# Table: location_events
#
# One row per RSSI/location sample received from a BLE gateway.
# Partitioned by event_ts (day) to keep query costs manageable.
# ---------------------------------------------------------------------------

resource "google_bigquery_table" "location_events" {
  project    = var.project_id
  dataset_id = google_bigquery_dataset.flowterra.dataset_id
  table_id   = "location_events"

  description        = "Raw location events streamed from ingest-fn."
  deletion_protection = false

  labels = var.labels

  time_partitioning {
    type  = "DAY"
    field = "event_ts"
  }

  clustering = ["customer_id", "site_id"]

  schema = jsonencode([
    {
      name        = "event_id"
      type        = "STRING"
      mode        = "REQUIRED"
      description = "Unique event ID (UUID generated by ingest-fn)."
    },
    {
      name        = "customer_id"
      type        = "STRING"
      mode        = "REQUIRED"
      description = "Tenant identifier extracted from the MQTT topic."
    },
    {
      name        = "site_id"
      type        = "STRING"
      mode        = "REQUIRED"
      description = "Site (building) identifier."
    },
    {
      name        = "gateway_id"
      type        = "STRING"
      mode        = "REQUIRED"
      description = "BLE gateway that detected the tag."
    },
    {
      name        = "tag_id"
      type        = "STRING"
      mode        = "REQUIRED"
      description = "BLE tag (person or asset) identifier."
    },
    {
      name        = "rssi"
      type        = "INTEGER"
      mode        = "REQUIRED"
      description = "Received Signal Strength Indicator (dBm)."
    },
    {
      name        = "area_id"
      type        = "STRING"
      mode        = "NULLABLE"
      description = "Resolved area/zone (from RSSI-to-zone lookup). Null if unresolvable."
    },
    {
      name        = "floor"
      type        = "INTEGER"
      mode        = "NULLABLE"
      description = "Floor number (from area config)."
    },
    {
      name        = "event_ts"
      type        = "TIMESTAMP"
      mode        = "REQUIRED"
      description = "Event timestamp from the gateway (used for partitioning)."
    },
    {
      name        = "ingested_at"
      type        = "TIMESTAMP"
      mode        = "REQUIRED"
      description = "Wall-clock time when ingest-fn processed the event."
    },
    {
      name        = "raw_payload"
      type        = "STRING"
      mode        = "NULLABLE"
      description = "Original MQTT payload JSON (for debugging/reprocessing)."
    }
  ])

  depends_on = [google_bigquery_dataset.flowterra]
}

# ---------------------------------------------------------------------------
# Table: geofence_events
#
# One row per geofence entry or exit alert.
# Partitioned by triggered_at (day).
# ---------------------------------------------------------------------------

resource "google_bigquery_table" "geofence_events" {
  project    = var.project_id
  dataset_id = google_bigquery_dataset.flowterra.dataset_id
  table_id   = "geofence_events"

  description        = "Geofence entry/exit alerts generated by ingest-fn."
  deletion_protection = false

  labels = var.labels

  time_partitioning {
    type  = "DAY"
    field = "triggered_at"
  }

  clustering = ["customer_id", "site_id"]

  schema = jsonencode([
    {
      name        = "alert_id"
      type        = "STRING"
      mode        = "REQUIRED"
      description = "Unique alert ID (also written to Firestore alerts/{alertId})."
    },
    {
      name        = "customer_id"
      type        = "STRING"
      mode        = "REQUIRED"
      description = "Tenant identifier."
    },
    {
      name        = "site_id"
      type        = "STRING"
      mode        = "REQUIRED"
      description = "Site identifier."
    },
    {
      name        = "tag_id"
      type        = "STRING"
      mode        = "REQUIRED"
      description = "BLE tag that triggered the alert."
    },
    {
      name        = "rule_id"
      type        = "STRING"
      mode        = "REQUIRED"
      description = "Geofence rule that matched."
    },
    {
      name        = "area_id"
      type        = "STRING"
      mode        = "REQUIRED"
      description = "Area/zone where the event occurred."
    },
    {
      name        = "event_type"
      type        = "STRING"
      mode        = "REQUIRED"
      description = "ENTRY or EXIT."
    },
    {
      name        = "triggered_at"
      type        = "TIMESTAMP"
      mode        = "REQUIRED"
      description = "Timestamp of the triggering location event (used for partitioning)."
    },
    {
      name        = "fcm_sent"
      type        = "BOOLEAN"
      mode        = "NULLABLE"
      description = "Whether an FCM push notification was sent for this alert."
    }
  ])

  depends_on = [google_bigquery_dataset.flowterra]
}
